# Generated by Django 5.0.3 on 2024-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcvcpfsetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(default='rvccpf', editable=False, max_length=30, verbose_name='Nome do Aplicativo')),
                ('nameapp', models.CharField(default='RVC - Controle de Produção Floresta', editable=False, max_length=30, verbose_name='Nome do Aplicativo')),
                ('description', models.TextField(max_length=254, verbose_name='Descrição do Aplicativo')),
                ('language', models.CharField(choices=[('pt-br', 'Portugues Brasil - (pt-br)'), ('en-us', 'Inglês (Estados Unidos) - (en-us)')], default='pt-BR', max_length=5, verbose_name='Idioma')),
                ('monetary_symbol', models.CharField(choices=[('R$', 'Real Brasil - (R$)'), ('$', 'Dollar - ($)'), ('€', 'Euro - (€)')], default='R$', max_length=2, verbose_name='Simbolo monetário')),
                ('thousand_separator', models.CharField(choices=[(',', 'Virgula - (,)'), ('.', 'Ponto - (.)')], default='.', max_length=1, verbose_name='Separador de milhar')),
                ('decimal_separator', models.CharField(choices=[(',', 'Virgula - (,)'), ('.', 'Ponto - (.)')], default=',', max_length=1, verbose_name='Separador de decimal')),
                ('date_separator', models.CharField(choices=[('/', 'Barra (/)'), ('-', 'Ifên (-)'), ('*', 'Asterisco (*)')], default='/', max_length=1, verbose_name='Separador de data')),
                ('date_format', models.CharField(choices=[('%d %m %Y', 'Alemanha (dd/mm/aaaa)'), ('%d %m %Y', 'Brasil (DD/MM/AAAA)'), ('%Y %m %d', 'China (aaaa/mm/dd)'), ('%d %m %Y', 'França (dd/mm/aaaa)'), ('%d %m %Y', 'França (dd/mm/aaaa)'), ('%m %d %Y', 'Inglês (mm/dd/aaaa)'), ('%d %m %Y', 'Espanha (dd/mm/aaaa)')], default='%d %m %Y', max_length=8, verbose_name='Formato de data')),
                ('extended_date_format', models.CharField(choices=[('%d, de %B de %Y', 'Dia, de mês de ano'), ('%B, %d de %Y', 'Mês, dia de ano'), ('%Y, %d de %B', 'Ano, dia de mês')], default='%d, de %B de %Y', max_length=15, verbose_name='Data por extenso')),
                ('time_format', models.CharField(choices=[('%H:%M:%S', '24 Horas (H:M:S)'), ('%I:%M:%S %p', 'AM/PM (H:M:S)'), ('%H:%M', '24 Horas (H:M)'), ('%I:%M %p', 'AM/PM (H:M)')], default='%H:%M:%S', max_length=11, verbose_name='Formato da hora')),
                ('decimal_places_ha', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=1, verbose_name='Casas Decimais (HA)')),
                ('decimal_places_mdc', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=1, verbose_name='Casas Decimais (MDC)')),
                ('decimal_places_m3', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=1, verbose_name='Casas Decimais (M³)')),
                ('decimal_places_valor', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=1, verbose_name='Casas Decimais (Valor)')),
                ('decimal_places_peso', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=1, verbose_name='Casas Decimais (Peso)')),
                ('decimal_places_porcentagem', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=1, verbose_name='Casas Decimais')),
                ('themes', models.CharField(choices=[('Thema padrão', 'Thema padrão'), ('themes/cerulean', 'Cerulean'), ('themes/cyborg', 'Cyborg'), ('themes/readable', 'Readable'), ('themes/simplex', 'Simplex'), ('themes/spruce', 'Spruce'), ('themes/superhero', 'SuperHero'), ('themes/united', 'United')], default='Thema padrão', max_length=30, verbose_name='Tema do sistema')),
                ('email_sistema', models.CharField(default='rvcsoftware@rvcsoftware.com.br', max_length=50, verbose_name='E-mail do Sistema')),
                ('file_extension', models.CharField(choices=[('.docx', '.docx'), ('.PDF', '.PDF'), ('.rvc', '.rvc')], default='.rvc', max_length=5, verbose_name='Extensão de arquivos')),
            ],
            options={
                'verbose_name': 'Configuração do App',
                'verbose_name_plural': 'Configurações do App',
            },
        ),
        migrations.DeleteModel(
            name='configuracoes',
        ),
    ]
