# Generated by Django 5.0.3 on 2024-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcvcpfsetup', '0004_configapp_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configapp',
            name='title',
            field=models.CharField(default='RVC (CP - Florestal)', max_length=50, verbose_name='Titulo da Aplicativo'),
        ),
        migrations.AlterField(
            model_name='configapp',
            name='short_name',
            field=models.CharField(default='CP - Florestal', max_length=50, verbose_name='Nome abreviado'),
        ),
    ]
